name: Anna Meyer, Komunikacja Techniczna, AFiB Vistula
title: Homework Project on Yerba Mate
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

# logo: "/assests/images/yerba.jpg"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/anna-meyer"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of a homework project for the Technical Communication course at Vistula University (Warsaw). </a>"