name: Anna Meyer, Komunikacja Techniczna, AFiB Vistula
title: Final Project Dummy
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

# logo: "/assests/images/cat-logo.jpg"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/anna-meyer"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the final project for the Technical Communication course at Vistula University (Warsaw). </a>"